SET SCHEMA DB2MOVIES; --ВСИЧКИ ЗАЯВКИ СА ЗА ТАЗИ СХЕМА

SELECT * FROM STUDIO;

--ЗА МАЛЛКА БУКВА
--ДВОЙНА КАВИЧКА ЗА ОБЕКТИ
SELECT NAME,ADDRESS, LOWER(NAME) LNAME FROM STUDIO
WHERE LOWER(NAME) ='mgm';

SELECT *
FROM  MOVIE
WHERE  YEAR > 1980 OR STUDIONAME ='MGM';

SELECT *
FROM  MOVIESTAR
WHERE  BIRTHDATE>= '1975-01-01';

--ПРОВЕРЯВА ДАЛИ СА ВКЛЮЧЕНИ
SELECT *
FROM  MOVIE
WHERE  YEAR IN(1977,1978,1980 );


SELECT *
FROM  MOVIE
WHERE  YEAR BETWEEN  1977 AND 1980;

------ЗАДАЧА---

SELECT ADDRESS
FROM STUDIO
WHERE NAME ='MGM';

SELECT NAME,BIRTHDATE FROM  MOVIESTAR
WHERE NAME = 'Sandra Bullock';

SET SCHEMA DB2SHIPS;
SELECT *
FROM SHIPS
WHERE  CLASS = 'Kongo' AND LAUNCHED >1915;

SELECT *
FROM CLASSES
WHERE CLASS = 'Kongo';

SELECT *
FROM  OUTCOMES
WHERE  SHIP = ' Bismarck';
