
CREATE  TABLE  T(
CODE INT NOT NULL PRIMARY KEY
);

---СЪЗДАВАНЕ НА ТАБЛИЦИ
CREATE  TABLE EMPLOYEE(
    ID INT NOT NULL,
    NAME VARCHAR(50),
    AGE INT,
    CODE INT REFERENCES T(CODE) --УПР2
    --CODE INT CONSTRAINT FK_EMP_T REFERENCES T(CODE)
    --СЛАГАНЕ НА ОГРАНИЧЕИЯ CONSTRAINT МОЖЕ ДА НЕ СЕ ПИШАТ
);

DROP TABLE  EMPLOYEE;

--ДОБАВЯНЕ НА ПЪРВИЧЕН КЛЮЧ
ALTER TABLE EMPLOYEE
ADD CONSTRAINT PK_EMP_ID PRIMARY KEY(ID);

-- ОГРАНИЧЕНИЕ НА ВЪЗРАСТТА
ALTER TABLE EMPLOYEE
ADD CONSTRAINT CK_EMP_AGE CHECK ( AGE > 0);

---ИЗТРИЙ CONSTRAINTS
ALTER TABLE EMPLOYEE
DROP  CONSTRAINT  CK_EMP_AGE;

ALTER TABLE EMPLOYEE
DROP  CONSTRAINT  PK_EMP_ID;

-- INSERT INTO EMPLOYEE(ID, NAME, AGE, CODE)
-- VALUES (3,'MARIA',33,2);
--
-- INSERT INTO EMPLOYEE(ID, NAME, AGE, CODE)
-- VALUES (6,'MARIA',33,2),
--         (4,'MARIA',33,2),
--         (5,'MARIA',33,2);

SELECT * FROM EMPLOYEE;

---ИЗТРИВАНЕ НА ЦЯЛАТА ТАБЛИЦА
DROP TABLE  EMPLOYEE;

---ID-ТО СЕ ГЕНЕРИРА АВТОМАТИЧНО
ALTER TABLE  EMPLOYEE
ALTER COLUMN  ID SET GENERATED  ALWAYS AS IDENTITY(START WITH 5 INCREMENT BY 1); ---ЗА ВСЯКО СУБД Е РАЗЛИЧНО

INSERT INTO EMPLOYEE( NAME, AGE, CODE)
VALUES ('MARIA', 33,2);

INSERT INTO EMPLOYEE( NAME, AGE, CODE)
VALUES ('MARIA',33,2),
        ('MARIA',33,2),
        ('MARIA',33,2);

DELETE FROM EMPLOYEE
WHERE ID = 13;

UPDATE EMPLOYEE
SET  AGE = 17
WHERE ID = 10;

--ВЪНШЕН КЛЮЧ В САМАТА ТАБЛИЦА

ALTER  TABLE  EMPLOYEE
ADD MANEAGER_ID INT;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMP_MNG FOREIGN KEY(MANEAGER_ID) REFERENCES  EMPLOYEE(ID);

--- АКО ЗНАЕМ ЦЯЛАТА ИНФОРМАЦИЯ
CREATE  TABLE EMPLOYEE1(
    ID INT NOT NULL GENERATED  ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) CONSTRAINT PK_EMP PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT CONSTRAINT  CK_AGE CHECK ( AGE > 0),
    CODE INT,
    MANEAGER_ID INT  REFERENCES  EMPLOYEE1(ID)
    CHECK ( ID != MANEAGER_ID )
);
